name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint code
      run: |
        pip install flake8
        flake8 services scripts

    - name: Run tests
      run: |
        # Assuming you have pytest tests in tests/ folder
        pip install pytest
        pytest tests/ --maxfail=1 --disable-warnings -q

  schema-drift-and-pipeline:
    runs-on: ubuntu-latest
    needs: build-and-test
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      TARGET_DB_URL: ${{ secrets.TARGET_DB_URL }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Detect Schema Drift
      run: |
        python scripts/detect_drift.py

    - name: Generate Ingestion Pipelines
      run: |
        python scripts/generate_pipeline.py

    - name: Commit Generated Pipelines
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add generated/
        git commit -m "Update generated ingestion pipelines" || echo "No changes to commit"
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}