name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint code (Flake8)
      run: |
        # Lint all Python files, avoid errors if folders don't exist
        if [ -d "services" ]; then flake8 services || echo "Flake8 issues in services"; fi
        if [ -d "scripts" ]; then flake8 scripts || echo "Flake8 issues in scripts"; fi
        # Lint root Python files
        flake8 . || echo "Flake8 issues in root"

    - name: Run tests (pytest)
      run: |
        if [ -d "tests" ]; then
          pip install pytest
          pytest tests/ --maxfail=1 --disable-warnings -q
        else
          echo "No tests folder found, skipping tests"
        fi

  schema-drift-and-pipeline:
    runs-on: ubuntu-latest
    needs: build-and-test
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      TARGET_DB_URL: ${{ secrets.TARGET_DB_URL }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Detect Schema Drift
      run: |
        python scripts/detect_drift.py || echo "No drift detected or script missing"

    - name: Generate Ingestion Pipelines
      run: |
        python scripts/generate_pipeline.py || echo "No pipelines generated or script missing"

    - name: Commit Generated Pipelines
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add generated/
        git commit -m "Update generated ingestion pipelines" || echo "No changes to commit"
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}